### ISSUE TITLE
您好，如何画出Fig.4(a)Different Heads的图片？

### ISSUE THREAD

**Issue by cpy0029** [AFeng-x/SMT#21]
您好，我使用您代码中给的vis.ipynb代码，但只画出了如下图一样的图。请问如何画出您论文中Figure 4(a) Different Heads一样的图？
![output](https://github.com/AFeng-x/SMT/assets/108877536/64cf0091-45ae-4a2e-baa0-5ac98b2894cc)

**Comment by AFeng-x** [comment]
你好，在smt的class Attention中的forward函数，参考下面代码，然后在vis代码中获取到self.head_1进行可视化即可。
def forward(self, x, H, W):
        B, N, C = x.shape
        if self.ca_attention == 1:
            v = self.v(x)
            s = self.s(x).reshape(B, H, W, self.ca_num_heads, C//self.ca_num_heads).permute(3, 0, 4, 1, 2)
            for i in range(self.ca_num_heads):
                local_conv = getattr(self, f"local_conv_{i + 1}")
                s_i= s[i]
                s_i = local_conv(s_i)
                if i ==0:
                   self.head_1 = s_i
                s_i = s_i.reshape(B, self.split_groups, -1, H, W)
                if i == 0:
                    s_out = s_i
                else:
                    s_out = torch.cat([s_out,s_i],2)
            s_out = s_out.reshape(B, C, H, W)
            s_out = self.proj1(self.act(self.bn(self.proj0(s_out))))
            self.modulator = s_out
            s_out = s_out.reshape(B, C, N).permute(0, 2, 1)
            x = s_out * v

**Comment by AFeng-x** [comment]
你好，在smt的class Attention中的forward函数，参考下面代码，然后在vis代码中获取到self.head_1进行可视化即可。
```
def forward(self, x, H, W):
        B, N, C = x.shape
        if self.ca_attention == 1:
            v = self.v(x)
            s = self.s(x).reshape(B, H, W, self.ca_num_heads, C//self.ca_num_heads).permute(3, 0, 4, 1, 2)
            for i in range(self.ca_num_heads):
                local_conv = getattr(self, f"local_conv_{i + 1}")
                s_i= s[i]
                s_i = local_conv(s_i)
                if i ==0:
                    self.head_1 = s_i
                s_i = s_i.reshape(B, self.split_groups, -1, H, W)
                if i == 0:
                    s_out = s_i
                else:
                    s_out = torch.cat([s_out,s_i],2)
            s_out = s_out.reshape(B, C, H, W)
            s_out = self.proj1(self.act(self.bn(self.proj0(s_out))))
            self.modulator = s_out
            s_out = s_out.reshape(B, C, N).permute(0, 2, 1)
            x = s_out * v
```

**Comment by cpy0029** [comment]
modulator = torch.abs((model.block1[-1].attn.head_1)).mean(1, keepdim=True) 请问是这样获取self.head_1吗 我这样还是有错误，提示AttributeError: 'Attention' object has no attribute 'head_1'

**Comment by cpy0029** [comment]
modulator = torch.abs((model.block1[-1].attn.head_1)).mean(1, keepdim=True)请问是这样获取吗，如果是这样的话我这里提示有错误AttributeError: 'Attention' object has no attribute 'head_1'

**Comment by AFeng-x** [comment]
是的，你需要在class init上写一个全局的self.head_1再去赋值

**Comment by cpy0029** [comment]
请问                if i ==0:
                    self.head_1 = s_i      如果i == 0 他只能输出第一个卷积的特征图，看您源码里一共有四个卷积，如何输出其他三个特征图呢？
